// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6XArZ3XAEleNiAXcIcYfWvFJrya9jAGs',
    appId: '1:165095080704:android:6eadd5ba73ba64b44da9e5',
    messagingSenderId: '165095080704',
    projectId: 'autobooking-b8782',
    databaseURL: 'https://autobooking-b8782-default-rtdb.firebaseio.com',
    storageBucket: 'autobooking-b8782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MS-7Pxi5WZTroY783W15UibtBnv2mno',
    appId: '1:165095080704:ios:ece3306608c249fe4da9e5',
    messagingSenderId: '165095080704',
    projectId: 'autobooking-b8782',
    databaseURL: 'https://autobooking-b8782-default-rtdb.firebaseio.com',
    storageBucket: 'autobooking-b8782.appspot.com',
    iosClientId: '165095080704-2muckrqipn6kk730q6ust2bp76al594n.apps.googleusercontent.com',
    iosBundleId: 'com.example.passenger',
  );
}
